In [ ]:
import numpy as np
print('Задание 1.')

a = np.matrix([[1, 0, 0, 0, 0],
               [0, 1, 0, 0, 0],
               [0, 0, 1, 0, 0],
               [0, 0, 0, 1, 0],
               [0, 0, 0, 0, 1]])
b = np.matrix([[3, 5, 2, -1, 0],
               [2, -3, 4, 6, 5],
               [4, 7, 3, -4, 5],
               [2, 8, 9, -3, 5],
               [5, -6, 2, 6, 3]])
print('Единичная матрица пятого порядка:')
print(a)
print('Обратная матрица для единичной:')
print(np.linalg.inv(a))
print('Матрица пятого порядка:')
print(b)
print('Обратная матрица для матрицы пятого порядка:')
print(np.linalg.inv(b))

Задание 1.
Единичная матрица пятого порядка:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Обратная матрица для единичной:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Матрица пятого порядка:
[[ 3  5  2 -1  0]
 [ 2 -3  4  6  5]
 [ 4  7  3 -4  5]
 [ 2  8  9 -3  5]
 [ 5 -6  2  6  3]]
Обратная матрица для матрицы пятого порядка:
[[ 0.08385707 -0.13682887  0.04327527 -0.01095349  0.17417849]
 [ 0.21637637  0.18441372  0.02172742 -0.09678578 -0.18225893]
 [-0.04776441 -0.12120668 -0.14670497  0.19895852  0.11492189]
 [ 0.23792422  0.26916861 -0.05494703 -0.11887233 -0.15891542]
 [-0.15101454  0.13934279  0.17902676 -0.07021009 -0.08026576]]


In [ ]:
print('Задание 2.')

c = np.matrix([[1, 2, 3],
               [4, 0, 6],
               [7, 8, 9]])

print('Матрица третьего порядка:')
print(c)
print('Определитель матрицы третьего порядка:')
print(np.linalg.det(c))

Задание 2.
Матрица третьего порядка:
[[1 2 3]
 [4 0 6]
 [7 8 9]]
Определитель матрицы третьего порядка:
59.999999999999986


In [ ]:
print('Задание 3.1')

print('Обратная матрица для матрицы третьего порядка:')
print(np.linalg.inv(c))

Задание 3.
Обратная матрица для матрицы третьего порядка:
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [ ]:
print('Задание 3.2')
d = np.matrix([[1, 6, 2, 0],
               [0, 0, 0, 0],
               [0, 0, 0, 0],
               [0, 0, 0, 0]])
print('Матрица четвертого порядка:')
print(d)
print('Ранг матрицы четвертого порядка:')
print(np.linalg.matrix_rank(d))

Задание 4.
Матрица четвертого порядка:
[[1 6 2 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Ранг матрицы четвертого порядка:
1


In [8]:
print('Задание 4.')
a1 = np.array([1, 5])
b1 = np.array([2, 8])
print('Вектор 1:', a1)
print('Вектор 2:', b1)
print('Скалярное произведение векторов:', np.dot(a1, b1))

Задание 4.
Вектор 1: [1 5]
Вектор 2: [2 8]
Скалярное произведение векторов: 42


In [15]:
print('Задание 5.')
a2 = np.array([1, 5, 0])
b2 = np.array([2, 8, 7])
c2 = np.array([7, 1.5, 3])
e = np.cross(a2, b2)
f = np.cross(b2, c2)
print(np.inner(e, c2))
print(np.inner(f, a2))

Задание 5.
228.5
228.5
